Repository AY2425S2-CS2103T-F13-1/tp, pull requests merged in 2025-04, with the labels that each got.

#102 Simplify the undo/redo
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedAddressBook.java
  src/main/java/seedu/address/model/exceptions/RedoException.java
  src/main/java/seedu/address/model/exceptions/UndoException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Enhancement, priority.Medium

#103 Remove Email from the Whole App
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteNoteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditNoteCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/patient/Address.java
  src/main/java/seedu/address/model/patient/Email.java
  src/main/java/seedu/address/model/patient/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/resources/view/PatientListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPatientAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPatientAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePatientAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPatientAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPatientsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPatientDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/patient/EmailTest.java
  src/test/java/seedu/address/model/patient/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/patient/PatientTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
  src/test/java/seedu/address/testutil/EditPatientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/PatientUtil.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
  src/test/java/seedu/address/ui/PatientCardTest.java
Labels: type.Task, priority.Medium, severity.Medium

#109 Increase results display
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement

#114 Add page breaks
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium

#119 Userguide draft v2
  README.md
  docs/UserGuide.md
  docs/images/ugFrontPagePhoto.png
  docs/index.md
Labels: type.Task, priority.High

#115 Add tests for undo/redo
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/model/VersionedAddressBookTest.java
Labels: type.Enhancement, priority.Medium

#160 Fix unclear error in deletenote
  src/main/java/seedu/address/logic/commands/DeleteNoteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteNoteCommandParser.java
Labels: priority.Medium

#161 Code cleanup
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterNoteCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/model/note/Note.java
  src/main/java/seedu/address/storage/JsonAdaptedNote.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/model/note/NoteTest.java
Labels: type.Task, priority.High

#224 Debug after PE-D
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/UndoRedoState2.puml
  docs/images/UndoRedoState2.png
  src/main/java/seedu/address/model/patient/Name.java
  src/main/java/seedu/address/model/patient/NameContainsKeywordsPredicate.java
Labels: type.Bug, severity.High

#221 Final bug fixes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/model/patient/Phone.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/patient/PhoneTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
Labels: type.Task, priority.High

#227 Fix little bugs in UG
  docs/UserGuide.md
Labels: type.Bug

#228 Typo in DG
  docs/DeveloperGuide.md
Labels: type.Bug
