Repository AY2425S2-CS2103T-F13-1/tp, pull requests merged in 2025-03, with the labels that each got.

#14 Add Daniel's Picture
  docs/images/danplatypus30.png
Labels: type.Task

#17 Add Andre details to AboutUs page
  docs/AboutUs.md
  docs/team/andrechia.md
Labels: type.Task

#28 Fix AboutUs.md and Developer Guide
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/images/andrechia.png
  docs/images/andrechia.png.jpg
  docs/images/benedictLee.png.jpg
  docs/images/benedictlee.png
Labels: type.Bug, priority.High

#31 Resolve naming convention for Benedict's image
  docs/images/benedictleejr.png
Labels: type.Bug, priority.High

#32 Fix naming issues for AboutUs
  docs/AboutUs.md
Labels: type.Bug, priority.High

#44 Add patient notes
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/model/note/Note.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/storage/JsonAdaptedNote.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/resources/view/PatientListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePatientAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPatientsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/NoteCommandParserTest.java
  src/test/java/seedu/address/model/note/NoteTest.java
  src/test/java/seedu/address/model/patient/PatientTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
Labels: type.Story, priority.High

#55 Add note tite and content when adding or modifying data
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/model/note/Note.java
Labels: type.Task, priority.High

#52 Add View Notes Command and Functionality
  src/main/java/seedu/address/logic/commands/ViewNotesCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewNotesCommandParser.java
  src/main/java/seedu/address/model/patient/PatientNoteFormatter.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/java/seedu/address/ui/PatientListPanel.java
  src/main/resources/view/PatientListCard.fxml
  src/test/java/seedu/address/logic/commands/ViewNotesCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ViewNotesCommandParserTest.java
  src/test/java/seedu/address/model/patient/PatientNoteFormatterTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/ui/PatientCardTest.java
  src/test/java/seedu/address/ui/PatientListPanelTest.java
Labels: priority.Medium

#56 Add warning when note to add is invalid
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/logic/parser/NoteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/note/Note.java
Labels: type.Task, priority.High

#60 Enhance command box UI
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement, priority.Medium

#66 Add Edit Note command
  src/main/java/seedu/address/logic/commands/EditNoteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditNoteCommandParser.java
  src/main/java/seedu/address/model/note/Note.java
  src/test/java/seedu/address/logic/commands/EditNoteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditNoteCommandParserTest.java
Labels: type.Enhancement, priority.Medium, severity.Medium

#65 Revamp of NeuroSync UI and Enhanced viewnotes Command Look
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ViewNotesCommand.java
  src/main/java/seedu/address/model/patient/PatientNoteFormatter.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/NotesDisplayPanel.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/neurosync-logo.png
  src/main/resources/styles.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/NotesDisplayPanel.fxml
  src/main/resources/view/PatientListCard.fxml
  src/main/resources/view/PatientListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  src/test/java/seedu/address/model/patient/PatientNoteFormatterTest.java
Labels: priority.High

#62 Add the deletenote command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteNoteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteNoteCommandParser.java
  src/test/java/seedu/address/logic/parser/DeleteNoteCommandParserTest.java
Labels: type.Enhancement, priority.High

#67 Add notes to user guide
  docs/UserGuide.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/patient/Address.java
  src/main/java/seedu/address/model/patient/Email.java
  src/main/java/seedu/address/model/patient/Name.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/patient/Phone.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: type.Enhancement, priority.Low

#78 Update Website Pages
  docs/UserGuide.md
  docs/_config.yml
  docs/images/Ui.png
  docs/index.md
Labels: priority.Low

#82 Prettify user guide
  docs/UserGuide.md
Labels: type.Task, priority.High

#84 Fix Neurosync Relases link
  docs/UserGuide.md
Labels: type.Bug, priority.Medium

#73 Add tests for DeleteNoteCommand
  src/main/java/seedu/address/logic/commands/DeleteNoteCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteNoteCommandTest.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
Labels: type.Task, priority.High

#86 Update Storage Class Diagram to include notes and patient
  build.gradle
  docs/UserGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: type.Task

#99 Remove Email from Model and Renamed User as Psychiatrist
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Task, priority.Low

#101 Add AddNote Sequence Diagram to Developers Guide
  docs/DeveloperGuide.md
  docs/diagrams/AddNoteSequenceDiagram.puml
  docs/images/AddNoteSequenceDiagram.png
Labels: type.Enhancement, priority.Low

#105 Add deletenote sequence diagram
  docs/DeveloperGuide.md
  docs/diagrams/DeleteNoteSequenceDiagram.puml
Labels: type.Enhancement, priority.Low
